#!/bin/sh
#
# Start the i2c/bmp180
#


case "$1" in
  start)
	printf "Starting i2c: "
	modprobe i2c-dev  && \
	modprobe bmp280-i2c && \
	modprobe i2c-bcm2835 
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping i2c: "
	modprobe -r i2c-dev && \
	modprobe -r bmp280-i2c && \
	modprobe -r i2c-bcm2835

	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?

