#!/bin/sh
#
# Start ntpd (pour mettre la date a jour en UTC)
#


case "$1" in
  start)
	printf "Starting ntpd: "
	ntpd -p pool.ntp.org
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping ntpd: "
	

	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?

