#!/bin/sh


mount /dev/mmcblk0p1 /mnt/

var=$(cat /proc/cmdline | grep -o root=/dev/mmcblk0p2)

[ -z "$var" ] && (echo "update switch to mmcblkk0p2"; 
scp dev@10.30.1.240:buildroot/buildroot-2022.02.2/output/images/rootfs.ext2 /dev/mmcblkp02;
sed -i -e 's/mmcblkp03/mmcblkp02' /mnt/cmdline.txt) || (echo "update switch to mmcblkk0p3"; 
scp dev@10.30.1.240:buildroot/buildroot-2022.02.2/output/images/rootfs.ext2 /dev/mmcblkp03;
sed -i -e 's/mmcblkp02/mmcblkp03' /mnt/cmdline.txt)

umount /mnt/

echo "reboot"

reboot
